export enum Auth {
  LOGIN = "/auth/login",
  REGISTER = "/auth/register",
  REGISTER_VERIFY_CODE = "/auth/register/verify-code",
  FORGOT_PASSWORD_MAIl = "/auth/forgot-password/email",
  FORGOT_PASSWORD_VERIFY_CODE = "/auth/forgot-password/verify-code",
  SET_PASSWORD = "/auth/set-password",
  REGISTER_SUCCESS = "/auth/register-success",
  LOGIN_REVERIFY_EMAIL = "/auth/login/re-verify-email",
}

export enum KaizenHubUrl {
  KAIZEN_HUB = "/kaizen-hub",
  KAIZEN_HUB_SEARCH = "/kaizen-hub-search",
  KAIZEN_HUB_INFO = "/kaizen-hub-info",
  KAIZEN_HUB_RECIPE = "/kaizen-hub-recipe",
  KAIZEN_HUB_REVIEW_RECIPE = "/kaizen-hub-review-recipe",
  KAIZEN_HUB_POST = "/kaizen-hub-post",
  KAIZEN_HUB_PREVIEW_POST = "/kaizen-hub-preview-post",
  KAIZEN_HUB_LOGIN = "/kaizen-hub-login",
  KAIZEN_HUB_REGISTER = "/kaizen-hub-register",
  KAIZEN_HUB_DRAFT = "/KAIZEN_HUB_DRAFT",
}

export enum App {
  PRIVACYANDPOLICY = "/privacyandpolicy",
  INDEX = "/",
  HOME = "/home",
  PARETO = "/pareto",
  WHYWHY = "/whywhy",
  WHYWHY_CREATE = "/whywhy/create",
  WHYWHY_VIEW = "/whywhy/view",
  WHYWHY_ANALYSIS_VIEW = "/whywhy/view/:sessionId",
  WHYWHY_HISTORY = "/whywhy/history",
  WHYWHY_INTERNAL_CASES = "/whywhy/internal-cases",
  WHYWHY_INTERNAL_CASE_DETAIL = "/whywhy/internal-cases/:caseId",
  REPORT_CREATION_PAGE = "/report-creation-page/:threadId",
  REPORT_PREVIEW_PAGE = "/report-preview/:threadId",
  FTA = "/fta",
  FTA_GENERAL_CHART = "/fta/general-chart",
  DIAGRAM = "/diagram",
  MODE = "/pareto/mode",
  SINGLE_MODE = "/pareto/singlemode",
  COMPARE_MODE_SELECTION = "/pareto/comparemode_selection",
  COMPARE_MODE = "/pareto/comparemode",
  GENERAL_CHART = "/diagram/general-chart",
  FISHBONE_DIAGRAM = "/fishbone-diagram",
  AI_FISHBONE_DIAGRAM = "/ai-fishbone-diagram",
  KAIZEN_HUB = "/kaizen-hub",
  KAIZEN_HUB_SEARCH = "/kaizen-hub-search",
  KAIZEN_HUB_INFO = "/kaizen-hub-info",
  KAIZEN_HUB_RECIPE = "/kaizen-hub-recipe",
  KAIZEN_HUB_REVIEW_RECIPE = "/kaizen-hub-review-recipe",
  KAIZEN_HUB_POST = "/kaizen-hub-post",
  KAIZEN_HUB_PREVIEW_POST = "/kaizen-hub-preview-post",
  KAIZEN_HUB_DRAFT = "/KAIZEN_HUB_DRAFT",
  KAIZEN_HUB_USER = "/kaizen-hub-user",
  YOUR_PROJECTS = "/your-projects",
  SETTINGS = "/settings",
  DATA_FROM_CLOUD = "/pareto/datafromcloud",
  DATA_FROM_CLOUD_FISHBONE = "/diagram/fishbone/datafromcloud",
  DATA_FROM_CLOUD_FTA = "/fta/datafromcloudFTA",
  FEATURE_CAUSE_TOOL = "/feature-cause-analysis-tool",
  PRODUCT_PARETO = "/product/pareto",
  PRODUCT_FISHBONE = "/product/fishbone",
  PRODUCT_WHYWHY = "/product/whywhy",
  PRODUCT_WEBSAVE = "/product/websave",
  PRODUCT_SERVICE_SUPPORT = "/product/service-support",
  CONTACT = "/contact",
  FEEDBACK = "/feedback",
  SOLUTIONS = "/solutions",
  SOLUTIONS_USE_CASES = "/solutions/use-cases",
  SOLUTIONS_BLOG = "/solutions/blog",
  SOLUTIONS_BLOG_POST = "/solutions/blog/:slug",
  COMPANY = "/company",
  COMPANY_INFO = "/company/info",
  COMPANY_TEAM = "/company/team",
}
