-- CreateEnum
CREATE TYPE "PlanTypeEnum" AS ENUM ('PLAN_A', 'PLAN_B', 'PLAN_C', 'PLAN_D', 'PLAN_E');

-- CreateEnum
CREATE TYPE "ActionEnum" AS ENUM ('LANDING_PAGE', 'PARENTO_CREATE_PAGE', 'PARENTO_SAVE_AS_CSV', 'PARENTO_SAVE_TYPED_DATA', 'PARENTO_CHOOSE_FONT_TEXT', 'PARENTO_CHOOSE_SIZE_TEXT', 'PARENTO_CHOOSE_COLOR_TEXT', 'FISHBONE_CREATE_PAGE', 'FISHBONE_SAVE_AS_CSV', 'FISHBONE_SAVE_TYPED_DATA', 'FISHBONE_AI_TEST', 'FTA_CREATE_PAGE', 'FTA_SAVE_AS_CSV', 'FTA_SAVE_TYPED_DATA', 'FTA_AI_TEST', 'WHYWHY_CREATE_PAGE', 'WHYWHY_DOWNLOAD_TEMPLATE_FILE', 'KAIZENHUB_MAIN_SCREEN', 'KAIZENHUB_POST_AND_VIEW');

-- CreateTable
CREATE TABLE "Plan" (
    "id" SERIAL NOT NULL,
    "type" "PlanTypeEnum" NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Plan_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Action" (
    "id" SERIAL NOT NULL,
    "type" "ActionEnum" NOT NULL,
    "name" VARCHAR(255),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Action_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PlanDetail" (
    "id" SERIAL NOT NULL,
    "planId" INTEGER NOT NULL,
    "actionId" INTEGER NOT NULL,
    "enableFlag" BOOLEAN,
    "limitedUsage" INTEGER,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PlanDetail_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "UserPlan" (
    "id" SERIAL NOT NULL,
    "userId" INTEGER NOT NULL,
    "planId" INTEGER NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "UserPlan_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "PlanDetail" ADD CONSTRAINT "PlanDetail_actionId_fkey" FOREIGN KEY ("actionId") REFERENCES "Action"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PlanDetail" ADD CONSTRAINT "PlanDetail_planId_fkey" FOREIGN KEY ("planId") REFERENCES "Plan"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "UserPlan" ADD CONSTRAINT "UserPlan_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "UserPlan" ADD CONSTRAINT "UserPlan_planId_fkey" FOREIGN KEY ("planId") REFERENCES "Plan"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
