export const contributors = [
  {
    id: 1,
    image: "/image/contributor_a.png",
    alt: "contributor-1",
    department: "アルミ加工製造部",
    name: "かいぜんマン",
  },
  {
    id: 2,
    image: "/image/contributor_b.png",
    alt: "contributor-2",
    department: "製造技術部",
    name: "てくにん",
  },
  {
    id: 3,
    image: "/image/contributor_c.png",
    alt: "contributor-1",
    department: "金属加工製造部",
    name: "メタ坊",
  },
  {
    id: 4,
    image: "/image/contributor_b.png",
    alt: "contributor-2",
    department: "製造技術部",
    name: "モノづくりマン",
  },
  {
    id: 5,
    image: "/image/contributor_d.png",
    alt: "contributor-1",
    department: "製造課金属加工",
    name: "てつまる",
  },
  {
    id: 6,
    image: "/image/contributor_e.png",
    alt: "contributor-2",
    department: "製造技術課",
    name: "ギジュ子",
  },
  {
    id: 7,
    image: "/image/contributor_a.png",
    alt: "contributor-1",
    department: "製造課鋳造",
    name: "ちゅうぞう",
  },
  {
    id: 8,
    image: "/image/contributor_b.png",
    alt: "contributor-2",
    department: "品質保証",
    name: "ヒンシツ番長",
  },
  {
    id: 9,
    image: "/image/contributor_b.png",
    alt: "contributor-2",
    department: "製造課物流",
    name: "はこびや",
  },
  {
    id: 10,
    image: "/image/contributor_h.png",
    alt: "contributor-2",
    department: "品質保証",
    name: "QCマスター",
  },
];
