export enum EventType {
  CREATE_NEW_PARETO_CHART = "CREATE_NEW_PARETO_CHART",
  UPLOAD_CSV_BEFORE_CHART = "UPLOAD_CSV_BEFORE_CHART",
  UPLOAD_CSV_AFTER_CHART = "UPLOAD_CSV_AFTER_CHART",
  DISPLAY_ERROR = "DISPLAY_ERROR",
  PARETO_CHECK_SAVE_DATA = "pareto_check_save_data",
  CHANGE_FONT_SIZE_LABEL_FIRST_RENDER = "CHANGE_FONT_SIZE_LABEL_FIRST_RENDER",
  CHANGE_FONT_SIZE_LABEL_FIRST_RENDER_AFTER = "CHANGE_FONT_SIZE_LABEL_FIRST_RENDER_AFTER",
  WHYWHY_THREAD_VISIBILITY_CHANGED = "WHYWHY_THREAD_VISIBILITY_CHANGED",
}

export enum EventChatType {
  LOAD_MORE_MESSAGES = "LOAD_MORE_MESSAGES",
  LAST_SNAPSHOT_MESSAGE = "LAST_SNAPSHOT_MESSAGE",
  GENERATE_CHART = "GENERATE_CHART",
  CALL_AI = "CALL_AI",
  CALL_AI_WITH_FIRST_NODE = "CALL_AI_WITH_FIRST_NODE",
}

export enum FontFamilyParetoChart {
  NotoSansJP_Regular = "NotoSansJP-Regular",
  BIZUDPGothic_Regular = "BIZUDPGothic_Regular",
  Osaka = "Osaka",
  MS_Gothic = "MS Gothic",
  IPAexGothic = "IPAexGothic",
  IPAexMincho = "IPAexMincho",
}

export enum ActionType {
  LANDING_PAGE = "LANDING_PAGE",
  PARENTO_CREATE_PAGE = "PARENTO_CREATE_PAGE",
  PARENTO_SAVE_AS_CSV = "PARENTO_SAVE_AS_CSV",
  PARENTO_SAVE_TYPED_DATA = "PARENTO_SAVE_TYPED_DATA",
  PARENTO_CHOOSE_FONT_TEXT = "PARENTO_CHOOSE_FONT_TEXT",
  PARENTO_CHOOSE_SIZE_TEXT = "PARENTO_CHOOSE_SIZE_TEXT",
  PARENTO_CHOOSE_COLOR_TEXT = "PARENTO_CHOOSE_COLOR_TEXT",
  FISHBONE_CREATE_PAGE = "FISHBONE_CREATE_PAGE",
  FISHBONE_SAVE_AS_CSV = "FISHBONE_SAVE_AS_CSV",
  FISHBONE_SAVE_TYPED_DATA = "FISHBONE_SAVE_TYPED_DATA",
  FISHBONE_AI_TEST = "FISHBONE_AI_TEST",
  FTA_CREATE_PAGE = "FTA_CREATE_PAGE",
  FTA_SAVE_AS_CSV = "FTA_SAVE_AS_CSV",
  FTA_SAVE_TYPED_DATA = "FTA_SAVE_TYPED_DATA",
  FTA_AI_TEST = "FTA_AI_TEST",
  WHYWHY_CREATE_PAGE = "WHYWHY_CREATE_PAGE",
  WHYWHY_DOWNLOAD_TEMPLATE_FILE = "WHYWHY_DOWNLOAD_TEMPLATE_FILE",
}

export enum TimeFormatTemplate {
  DATE_TIME = "yyyy/MM/dd HH:mm",
  TIME = "HH:mm",
}
