"""
LangChain用のコールバックハンドラー
"""
from typing import Any, Optional, Union
from uuid import UUID

import structlog
from langchain.callbacks.base import AsyncCallbackHandler
from langchain.schema import LLMResult
from opentelemetry import metrics

from why_why_chat_ai.api.telemetry import request_id_var, trace_id_var

logger = structlog.get_logger(__name__)


class TokenUsageCallback(AsyncCallbackHandler):
    """
    LLMトークン使用量を監視するコールバックハンドラー
    """

    def __init__(self, thread_id: Optional[str] = None):
        """
        コールバックハンドラーの初期化

        Args:
            thread_id: スレッドID（分析セッションの識別子）
        """
        super().__init__()
        self.thread_id = thread_id

        # OpenTelemetryメトリクスの取得
        meter = metrics.get_meter(__name__)

        # カスタムメトリクスの定義
        self.token_input_counter = meter.create_counter(
            name="llm.token.input.count",
            description="Number of input tokens used by LLM",
            unit="token"
        )

        self.token_output_counter = meter.create_counter(
            name="llm.token.output.count",
            description="Number of output tokens generated by LLM",
            unit="token"
        )

        self.token_total_counter = meter.create_counter(
            name="llm.token.total.count",
            description="Total number of tokens used by LLM",
            unit="token"
        )

    async def on_llm_end(
        self,
        response: LLMResult,
        *,
        run_id: UUID,
        parent_run_id: Optional[UUID] = None,
        **kwargs: Any,
    ) -> None:
        """
        LLM呼び出し終了時の処理

        Args:
            response: LLMの応答結果
            run_id: 実行ID
            parent_run_id: 親実行ID
            kwargs: その他のキーワード引数
        """
        try:
            # llm_outputからトークン使用量を取得
            llm_output = response.llm_output
            if not llm_output:
                return

            token_usage = llm_output.get("token_usage")
            if not token_usage:
                return

            # トークン数を取得
            input_tokens = token_usage.get("prompt_tokens", 0)
            output_tokens = token_usage.get("completion_tokens", 0)
            total_tokens = token_usage.get("total_tokens", input_tokens + output_tokens)

            # モデル名を取得（高カーディナリティ対策のためファミリー名に丸める）
            model_name = llm_output.get("model_name", "unknown")
            if "gemini-1.5" in model_name.lower():
                model_family = "gemini-1.5"
            elif "gemini" in model_name.lower():
                model_family = "gemini"
            elif "gpt-4" in model_name.lower():
                model_family = "gpt-4"
            elif "gpt-3.5" in model_name.lower():
                model_family = "gpt-3.5"
            else:
                model_family = "other"

            # メタデータの準備
            attributes = {
                "model_name": model_family,
                "thread_id": self.thread_id or "unknown",
                "request_id": request_id_var.get() or "unknown",
            }

            # メトリクスの記録
            if input_tokens > 0:
                self.token_input_counter.add(input_tokens, attributes)
            if output_tokens > 0:
                self.token_output_counter.add(output_tokens, attributes)
            if total_tokens > 0:
                self.token_total_counter.add(total_tokens, attributes)

            # デバッグログ
            logger.debug(
                "Token usage recorded",
                model_name=model_name,
                model_family=model_family,
                input_tokens=input_tokens,
                output_tokens=output_tokens,
                total_tokens=total_tokens,
                thread_id=self.thread_id,
                request_id=request_id_var.get(),
                trace_id=trace_id_var.get(),
            )

        except Exception as e:
            # エラーが発生してもLLMの処理は継続
            logger.error(
                "Failed to record token usage",
                error=str(e),
                exc_info=True,
            )

    async def on_llm_error(
        self,
        error: Union[Exception, KeyboardInterrupt],
        *,
        run_id: UUID,
        parent_run_id: Optional[UUID] = None,
        **kwargs: Any,
    ) -> None:
        """
        LLMエラー時の処理

        Args:
            error: 発生したエラー
            run_id: 実行ID
            parent_run_id: 親実行ID
            kwargs: その他のキーワード引数
        """
        logger.error(
            "LLM error occurred",
            error=str(error),
            thread_id=self.thread_id,
            request_id=request_id_var.get(),
            trace_id=trace_id_var.get(),
            exc_info=True,
        )
